liip_imagine:

    filter_sets:

        my_thumb :

            # adjust the image quality to 75%

            quality: 75

            filters:

                thumbnail:

                    size: [360, 230]

                    mode : outbound