# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "imagick"

    # your filter sets are defined here
    filter_sets:
        # use the default cache configuration
        cache: ~        
        my_thumb:
            # adjust the image quality to 75%
            quality: 75
            filters:
                thumbnail:
                    size: [360, 230]
                    mode : outbound